SRCS := blink.c system_stm32f30x.c
EXTRA_LINK_OBJS := startup_stm32f30x.s
PROGRAM_NAME := blink

CPU := cortex-m3
FAMILY := STM32F3

OPENOCD := /home/kmod/arm-cross/bin/openocd

include ../common/stm32_bare/Makefile.include
